services:
  nginx:
    image: velvet-nginx:20241001
    ports:
      - '1935:1935'
      - '443:443'
      - '80:80'
    restart: unless-stopped
    stdin_open: true
    tty: true
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./store:/velvet/store:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
