services:
  db:
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_DB: velvet
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
    image: postgres:17
    ports:
      - '127.0.0.1:5432:5432'
    restart: unless-stopped
    shm_size: 128mb
    volumes:
      - ../velvet_db:/var/lib/postgresql/data
  velvet:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - db
    environment:
      DJANGO_SETTINGS_MODULE: config.settings_dev
    image: velvet:20240807
    ports:
      - '0.0.0.0:80:8000'
    restart: unless-stopped
    stdin_open: true
    stop_signal: SIGINT
    tty: true
    volumes:
      - ./.pg_service.conf:/root/.pg_service.conf
      - ./app:/velvet
      - ./store:/velvet/store
    working_dir: /velvet
