# Generated by Django 5.0.2 on 2024-05-10 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('name', models.CharField(max_length=200)),
                ('price', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
