# Generated by Django 5.0.2 on 2024-05-10 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.TextField(blank=True)),
                ('article_type', models.PositiveSmallIntegerField(choices=[(1, 'Article'), (2, 'Youtube'), (4, 'Album'), (5, 'Stream')], default=1)),
                ('cache_content', models.TextField()),
                ('code', models.TextField(blank=True)),
                ('content', models.TextField()),
                ('cover', models.CharField(blank=True, max_length=100)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('is_comments', models.BooleanField(default=True)),
                ('is_published', models.BooleanField(default=True)),
                ('status', models.CharField(blank=True, max_length=100)),
                ('title', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
